version: '3'

services:
  builder:
    container_name: stay-active-builder
    build:
      context: .
      args:
        OS: windows
        ARCH: amd64
    volumes:
      - ./bin:/home/app/bin
    environment:
      - TAG=example
