name: Build and release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build Windows Compiler
        run: docker build --build-arg OS=windows -t windows-builder .

      - name: Build Linux Compiler
        run: docker build --build-arg OS=linux -t linux-builder .

      - name: Build Windows amd64 Binaries
        run: docker run --rm -v ./bin:/home/app/bin -e TAG=${{ steps.get_tag.outputs.tag }} -e EXT=exe windows-builder

      - name: Build Linux amd64 Binaries
        run: docker run --rm -v ./bin:/home/app/bin -e TAG=${{ steps.get_tag.outputs.tag }} -e EXT=bin linux-builder

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: ${{ steps.get_tag.outputs.tag }}
          body: |
            Release ${{ steps.get_tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Windows amd64 binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/stay_active-${{ steps.get_tag.outputs.tag }}.windows-amd64.exe
          asset_name: stay_active-${{ steps.get_tag.outputs.tag }}.windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux amd64 binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/stay_active-${{ steps.get_tag.outputs.tag }}.linux-amd64.bin
          asset_name: stay_active-${{ steps.get_tag.outputs.tag }}.linux-amd64.bin
          asset_content_type: application/octet-stream
