name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, darwin, linux]
        goarch: [amd64]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
          CC: x86_64-w64-mingw32-gcc
        run: go build -modfile=./app/go.mod -o mouse_mover-${{ matrix.goos }}-${{ matrix.goarch }} ./app/main.go

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mouse_mover-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: mouse_mover-${{ matrix.goos }}-${{ matrix.goarch }}
          tag: ${{ github.ref }}
          overwrite: true
